### ISSUE TITLE
Doesn't take into account multiple nvim instances

### ISSUE THREAD

**Issue by Amzd** [sammce/fleeting.nvim#1]
Cool plug-in! I often run multiple instances of neovim though and wouldn't want the tracked time to tick multiple times as fast, as far as I can tell that's not handled.

**Comment by sammce** [comment]
Thanks, I'm currently working on an update which addresses this issue. Should be done in the next day or so!

**Comment by sammce** [comment]
Fixed in [581455a](https://github.com/sammce/fleeting.nvim/commit/581455a9eb6412e494961a26ab8879161802d9cb) 👍.

I updated the format of the log file, but it should automatically convert your old one keeping the time intact.
